#!/usr/bin/env python3
"""Generate SPEC.md Appendix A.2/A.3, the known-answer vectors (stdlib only).

    gen_appendix.py --print            print the generated block
    gen_appendix.py --check            exit 1 if SPEC.md's block differs
    gen_appendix.py --write            rewrite SPEC.md's block in place

Each conformance trace spec/conformance/traces/NN-name.json is the
known-answer vector KAV-NN. The ID comes from the file's number, so it is
stable. The trace file stays the full machine-readable vector; the table
summarises it: purpose (the trace's own description), seed, input, frame
count, end state, checkpoint digests and the final frame digest.

The block sits between the BEGIN/END markers below and is never edited by
hand: the traces are the one editable representation. bin/verify.sh runs
--check, and its self-test proves that a hand-edited digest is rejected.
"""

import argparse
import glob
import hashlib
import importlib.util
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
BEGIN = ("<!-- BEGIN KAV: generated by spec/conformance/gen_appendix.py "
         "from spec/conformance/traces; do not edit by hand -->")
END = "<!-- END KAV -->"
ACTIONS = ("left", "right", "soft_drop", "hard_drop", "rotate_cw",
           "rotate_ccw", "rotate_180", "hold")


def _runner():
    spec = importlib.util.spec_from_file_location(
        "conformance_run", os.path.join(HERE, "run.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def kav_id(path):
    number = os.path.basename(path).split("-", 1)[0]
    if not number.isdigit():
        raise ValueError(f"{path}: trace file names start with a number")
    return f"KAV-{int(number):02d}"


def cell(text):
    return str(text).replace("|", "\\|").replace("\n", " ")


def input_summary(events):
    if not events:
        return "none"
    counts = {}
    for _, action, down in events:
        counts.setdefault(action, [0, 0])[0 if down else 1] += 1
    parts = []
    for action in ACTIONS:
        if action in counts:
            press, release = counts[action]
            parts.append(f"`{action}` {press}↓ {release}↑")
    first, last = events[0][0], events[-1][0]
    return f"{len(events)} events, frames {first}–{last}: " + ", ".join(parts)


FIRST_PLAY_FRAME = 91  # SPEC §9.1: frames 0-90 are the boot sequence


def checkpoints(trace):
    """Frames 1/4, 1/2 and 3/4 of the way from the first play frame to the
    last frame, each rounded down to a digested frame, with their digests.
    (The boot frames are the same in every vector, so they pin nothing.)"""
    every, frames, digests = trace["digest_every"], trace["frames"], trace["digests"]
    start = min(FIRST_PLAY_FRAME, frames - 1)
    out = []
    for num in (1, 2, 3):
        index = (start + (frames - 1 - start) * num // 4) // every
        out.append((index * every, digests[index]))
    return out


def generate(traces_dir):
    paths = sorted(glob.glob(os.path.join(traces_dir, "*.json")),
                   key=os.path.basename)
    if not paths:
        raise ValueError(f"no traces in {traces_dir}")
    runner = _runner()
    traces = []
    for p in paths:
        with open(p) as fh:
            t = json.load(fh)
        problems = runner.validate(t, p)
        if problems:
            raise ValueError("; ".join(problems))
        final_digest = hashlib.sha256(bytes.fromhex(t["final"]["frame_hex"])).hexdigest()
        if final_digest != t["digests"][-1]:
            raise ValueError(f"{p}: final.frame_hex does not match the last digest")
        traces.append((kav_id(p), t))
    ids = [k for k, _ in traces]
    if len(set(ids)) != len(ids):
        raise ValueError("two trace files share a number")

    lines = [BEGIN, "",
             f"Trace set: {len(traces)} vectors, "
             f"`sha256(traces)` = `{runner.trace_set_digest(paths)}`.", "",
             "**Table A.2a. The vectors.** Frames count from 0, the first "
             "countdown frame; play starts at frame 91 (§9.1).", "",
             "| ID | Trace | Purpose | Seed | Input | Frames | End state |",
             "|---|---|---|---|---|---|---|"]
    for k, t in traces:
        f = t["final"]
        end = f"{f['phase']}, score {f['score']}, level {f['level']}"
        lines.append(f"| {k} | `{t['name']}` | {cell(t['description'])} | {t['seed']} "
                     f"| {input_summary(t['events'])} | {t['frames']} | {end} |")
    lines += ["", "**Table A.2b. Checkpoint and final digests** (§9.4). The "
              "checkpoints are the frames ¼, ½ and ¾ of the way from frame 91, "
              "the first play frame, to the last frame, each rounded down to a "
              "digested frame. The final frame is frame `frames − 1`; its bytes "
              "are the observation's `frame_hex`.", "",
              "| ID | Checkpoints (frame: SHA-256) | Final frame SHA-256 |",
              "|---|---|---|"]
    for k, t in traces:
        cps = "<br>".join(f"{frame}: `{d}`" for frame, d in checkpoints(t))
        lines.append(f"| {k} | {cps} | `{t['digests'][-1]}` |")
    lines += ["", END]
    return "\n".join(lines)


def current(spec_text):
    start, end = spec_text.find(BEGIN), spec_text.find(END)
    if start < 0 or end < start:
        return None
    return spec_text[start:end + len(END)]


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--print", action="store_true", dest="show")
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    ap.add_argument("--traces", default=os.path.join(HERE, "traces"))
    ap.add_argument("--spec", default=os.path.join(ROOT, "SPEC.md"))
    args = ap.parse_args(argv)

    block = generate(args.traces)
    if args.show:
        print(block)
        return 0
    with open(args.spec, encoding="utf-8") as fh:
        text = fh.read()
    have = current(text)
    if args.write:
        if have is None:
            print(f"FAIL: no KAV markers in {args.spec}")
            return 1
        with open(args.spec, "w", encoding="utf-8") as fh:
            fh.write(text.replace(have, block))
        print(f"wrote the KAV block of {args.spec}")
        return 0
    if have is None:
        print(f"FINDING {args.spec}: no KAV block (markers missing)")
        print("FAIL: SPEC appendix check")
        return 1
    if have != block:
        for n, (a, b) in enumerate(zip(have.splitlines(), block.splitlines()), 1):
            if a != b:
                print(f"FINDING {args.spec}: KAV block line {n} differs from the "
                      f"generated one:\n  spec:      {a[:160]}\n  generated: {b[:160]}")
                break
        else:
            print(f"FINDING {args.spec}: KAV block length differs from the generated one")
        print("FAIL: SPEC appendix check")
        return 1
    print("PASS: SPEC Appendix A matches the traces")
    return 0


if __name__ == "__main__":
    sys.exit(main())
