"The Hy conformance driver (spec/conformance/README.md).

    python -m hy -m tetris_hy.conformance TRACE.json [TRACE.json ...]

For each trace, in argument order, prints one JSON line: the digests and
the final observation (SPEC §12) that this engine computes from the
trace's seed, frames, digest_every and events. It never reads the trace's
own digests or final: those belong to the runner."

(import json sys)
(import tetris_hy.engine [init step phase])
(import tetris_hy.frame [render-codes frame-bytes digest])

(defn observe [s]
  "The observation of §12."
  (setv [shape rot row col] (:active s)
        hold (:hold s))
  {"phase" (phase s)
   "score" (:score s)
   "level" (:level s)
   "lines" (:lines s)
   "high_score" (:high-score s)
   "active" {"shape" shape "rotation" rot "row" row "col" col}
   "hold" (when hold {"shape" (get hold 0) "rotation" (get hold 1)})
   "frame_hex" (.hex (frame-bytes (render-codes s)))})

(defn events-by-frame [events]
  "[frame action down] triples → {frame [#(action down) ...]}, in order."
  (setv out {})
  (for [[k action down] events]
    (.append (.setdefault out (int k) []) #(action (bool down))))
  out)

(defn run-trace [trace]
  "Replay a trace's input on a fresh engine."
  (setv frames (int (get trace "frames"))
        every (int (get trace "digest_every"))
        inputs (events-by-frame (get trace "events"))
        s (init (get trace "seed"))
        digests [])
  (for [k (range frames)]
    (setv s (step s (.get inputs k #())))
    (when (or (= 0 (% k every)) (= k (- frames 1)))
      (.append digests (digest (render-codes s)))))
  {"name" (.get trace "name") "digests" digests "final" (observe s)})

(defn make-trace [name description seed frames events [digest-every 1] [covers #()]]
  "A trace (§12) of this engine's run on `events` ([frame action down]
  triples). Sealed traces are generated by the sealing implementation
  only; this is for saving ad-hoc runs, such as the simulator's."
  (import tetris_hy [SPEC-VERSION])
  (setv trace {"format" "17x9-tetris-trace"
               "spec_version" SPEC-VERSION
               "name" name
               "description" description
               "covers" (list covers)
               "seed" (int seed)
               "frames" (int frames)
               "digest_every" (int digest-every)
               "events" (sorted (lfor [k action down] events [(int k) action (bool down)])
                                :key (fn [e] (get e 0)))}
        result (run-trace trace))
  (| trace {"digests" (get result "digests") "final" (get result "final")}))

(defn main [[argv None]]
  (setv paths (if (is argv None) (cut sys.argv 1 None) argv))
  (when (not paths)
    (print __doc__ :file sys.stderr)
    (return 2))
  (for [path paths]
    (with [fh (open path)]
      (print (json.dumps (run-trace (json.load fh)) :sort-keys True))))
  0)

(when (= __name__ "__main__")
  (sys.exit (main)))
