(ns tetris.displays.caps
  "The display tables of wal.sh/tools/display v0.2.1: presets and palettes.

  They are data, not code (spec section 4): resources/tetris/displays/
  capabilities.edn, generated by `bb caps:edn` from the pinned
  capabilities.json next to it, and never edited by hand. The EDN is
  exactly the JSON's `edn-keys`, keys keywordized; a test holds the two
  equal, and the JSON to its sha256 pin.

  The table is read at compile time (a macro), so the same namespace works
  on the JVM, under babashka and, in principle, in ClojureScript."
  #?(:clj (:require [clojure.edn :as edn]
                    [clojure.java.io :as io]))
  #?(:cljs (:require-macros [tetris.displays.caps :refer [inline-edn]])))

(def spec-version "The pinned contract." "0.2.1")

(def json-resource "tetris/displays/capabilities.json")
(def edn-resource "tetris/displays/capabilities.edn")

(def json-sha256
  "sha256 of the pinned capabilities.json (inputs/wal-sh-display-0.2.1/PROVENANCE)."
  "11fdc2b39380c84bad9702fa9aefe402e8761a1b082467b2ef27487edbb88275")

(def edn-keys
  "The top-level capabilities.json keys the EDN carries."
  [:spec :default :formats :max :reservation :palette :palettes :displays])

#?(:clj
   (defmacro inline-edn
     "The EDN resource at `path`, read at compile time."
     [path]
     (edn/read-string (slurp (io/resource path)))))

(def caps "The display tables." (inline-edn "tetris/displays/capabilities.edn"))

(def spec-default
  "The default the v0.2.1 advertisement names (cga40)."
  (:default caps))

(def default-display
  "This repo's default wherever one is needed: green-building, the 9x17
  facade the SPEC engine draws on (user direction, 2026-09-11). It differs
  from the spec's `spec-default` (cga40) on purpose; the relay advertises
  whichever default it resolves an omitted `display` to."
  "green-building")

(def display-names
  "Every preset name (the `d` values), sorted."
  (vec (sort (map name (keys (:displays caps))))))

(def palette-names
  "Every named palette, sorted."
  (vec (sort (map name (keys (:palettes caps))))))

(def preset-order
  "The presets in the order of the spec's Presets table (section 4; a JSON
  object's key order means nothing). It breaks w x h ties when a
  Blinkenlights packet picks its display: tetris before c64, dc32 before
  gameboy, green-building before remote."
  ["cga40" "tetris" "green-building" "dc32" "gameboy" "trs80" "c64" "ws2812" "hub75"
   "blinkenlights" "arcade" "remote"])

(defn preset
  "The preset named `d` (string or keyword), or nil."
  [d]
  (when (or (string? d) (keyword? d))
    (get-in caps [:displays (keyword d)])))

(defn display-for
  "The first preset in table order whose grid is w x h, or nil."
  [w h]
  (first (filter #(= [w h] ((juxt :w :h) (preset %))) preset-order)))

(defn palette
  "The palette named `p` (string or keyword): 2 to 16 \"#RRGGBB\" entries, or nil."
  [p]
  (when (or (string? p) (keyword? p))
    (get-in caps [:palettes (keyword p)])))
